import {
    ButtonModule,
    BreadcrumbModule,
    MegaMenuModule,
    MenuModule,
    PanelMenuModule,
    SelectButtonModule,
    CalendarModule,
    AutoCompleteModule,
    SplitButtonModule,
    DropdownModule,
    RadioButtonModule,
    InputTextareaModule,
    InputTextModule,
    ListboxModule,
    PasswordModule,
    PanelModule,
    DataTableModule,
    SharedModule,
    TabMenuModule,
    MessagesModule
} from 'primeng/primeng';

export const primeModules = [
    ButtonModule,
    BreadcrumbModule,
    MegaMenuModule,
    MenuModule,
    PanelMenuModule,
    SelectButtonModule,
    CalendarModule,
    AutoCompleteModule,
    SplitButtonModule,
    DropdownModule,
    ListboxModule,
    RadioButtonModule,
    InputTextareaModule,
    InputTextModule,
    PasswordModule,
    PanelModule,
    DataTableModule,
    SharedModule,
    MessagesModule,
    TabMenuModule,
]